In [2]:
import numpy as np

In [5]:
#配列の先頭、2番目、最後の要素を調べる
a = np.array([10,20,30,40,50])
a[0]
a[1]
a[-1]

50

In [14]:
#配列の3番目の値を99に変更する
a = np.array([10,20,30,40,50])
a[2] = 99
a[3] = 11
a

array([10, 20, 99, 11, 50])

In [17]:
#3行3列目の要素にアクセスする
data = [10,20,30,40,50,60,70,80,90]
a = np.array(data).reshape(3,3)    #3行3列の配列に変換
a
a[0,0]
a[1,2]

60

In [20]:
#1次元配列aから2次元配列bを作る
a = np.array([10,20,30,40])
b = a.reshape(4,1)  #配列aから配列bを作る
a
b

array([[10],
       [20],
       [30],
       [40]])

In [24]:
#reshape()で作った配列bを変更すると元の配列aも変更される
a = np.array([10,20,30,40])
b = a.reshape(4,1)

a is b

b[0,0] = 99
b
a

array([99, 20, 30, 40])

In [31]:
#配列をスライスする
data = np.array([0,10,20,30,40,50,60,70,80,90])
data[:] #全ての要素（複製したことになる）

data[:4] #最初から3番目までのインデックス

data[4:] #インデックス番号4番目以降

data[3:7] #インデックス番号3〜6番目まで

data[::2] #先頭から1個飛び

array([ 0, 20, 40, 60, 80])

In [32]:
#要素を逆順にした配列を作る
data = np.array([0,10,20,30,40,50,60,70,80,90])

data[::-1] #末尾から一個ずつ取り出す

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [36]:
#多次元配列のスライス
data = [10,20,30,40,50,60,70,80,90]
a = np.array(data).reshape(3,3)

a[:2,] #0~1行目の全ての列

a[:,1:] #全ての行1列目以降

a[1:,1:] #1行目以降、1列目以降

array([[50, 60],
       [80, 90]])

In [38]:
#astype()関数にてスライスと同時に型変換する
data = [2.1,3.5,2.5,4.3,5.1,1.6]
a = np.array(data).reshape(3,2)

a2 = a[:2,].astype(int) #最初の2行を取り出す際に整数に変換する
a2 

array([[2, 3],
       [2, 4]])

In [39]:
#配列の要素を順に取り出す
data = np.array([0,10,20,30,40,50,60,70,80,90])
for item in data :
    print(item)

0
10
20
30
40
50
60
70
80
90


In [40]:
#enumerate()関数にて要素を順に取り出す（繰り返し回数を表示して）
words = ["flower","bird","wind","moon"]
for i, item in enumerate(words,1) :
    print(i,item)

1 flower
2 bird
3 wind
4 moon


In [43]:
#ndenumerate()関数にて多次元配列の要素を順に取り出す
data = np.array([10,20,30,40,50,60]).reshape(2,3)
print(data)

for i,item in np.ndenumerate(data) : #多次元配列から位置と要素を取り出す
    print(i,item)  #iには（行、列）が入る

[[10 20 30]
 [40 50 60]]
(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [44]:
#比較式にて5以上の値を抽出する
a = np.array([3,1,4,1,5,9,2,6,5,3,5,8,9,7,9,3])
a[a>=5] #5以上の値を抽出する

array([5, 9, 6, 5, 5, 8, 9, 7, 9])

In [48]:
#偶数、奇数を分ける
a = np.array([2,1,54,6,334,67,3,2,6,8,9,35,74,63,75,43,546,76,35,36,26,74,356,7552,657,354,93])

a[a%2 == 0] #偶数

a[a%2 == 1] #奇数

array([  1,  67,   3,   9,  35,  63,  75,  43,  35, 657,  93])

In [52]:
#多次元配列から5より大きい値を抽出する
a = np.array([3,1,4,1,5,9,2,6,5,3,5,8,9,7,9,3])
b = a.reshape(4,4)
b

b[b>5]

array([9, 6, 8, 9, 7, 9])

In [53]:
#5以上の奇数を取り出す
a = np.array([3,1,4,1,5,9,2,6,5,3,5,8,9,7,9,3])
a[(a>=5)&(a%2==1)] #論理積（5以上かつ奇数）

array([5, 9, 5, 5, 9, 7, 9])

In [54]:
#2または3の倍数
a[(a%2==0) | (a%3==0)] #論理和（2または3の倍数）

array([3, 4, 9, 2, 6, 3, 8, 9, 9, 3])

In [55]:
#3の倍数ではない値
a[~(a%3==0)] #論理否定（3の倍数ではない）

array([1, 4, 1, 5, 2, 5, 5, 8, 7])

In [60]:
#条件に合う要素を変更する。偶数は0、奇数は1に置き換える
a = np.array([3,1,4,1,5,9,2,6,5,3,5,8,9,7,9,3])
a = a.reshape(4,4)
a

a[a%2==0] = 0 #偶数を0に変換
a

a[a%2==1] = 1 #奇数を1に変換
a

array([[1, 1, 0, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [62]:
#sort()メソッドにて配列を昇順にソートする
a = np.array([3,1,4,1,5,9,2,6,5,3,5,8,9,7,9,3]) #要素を昇順に並べる
a.sort()
a

array([1, 1, 2, 3, 3, 3, 4, 5, 5, 5, 6, 7, 8, 9, 9, 9])

In [63]:
#ソート済みの配列を作る
a = np.sort([4,2,6,4,7,3,7,3,7,35,74,74,95,43])
a

array([ 2,  3,  3,  4,  4,  6,  7,  7,  7, 35, 43, 74, 74, 95])

In [64]:
#降順に配列を作る
a = np.array([3,1,4,5,9,2,6,5,3,5,8,9,7,9,3])
a_decend = np.sort(a)[::-1] #ソートした後で逆順に並べ替える
a_decend

array([9, 9, 9, 8, 7, 6, 5, 5, 5, 4, 3, 3, 3, 2, 1])

In [66]:
#配列の全ての要素に5を足す
A = np.array([10,20,30,40]).reshape(2,2)
print(A)

B = A + 5 #配列の要素に5を足す
print(B)

[[10 20]
 [30 40]]
[[15 25]
 [35 45]]


In [69]:
#配列の全ての要素に引き算、掛け算、割り算を行う
A - 5

A * 5

A/5

array([[2., 4.],
       [6., 8.]])

In [70]:
#ベクトルaを行列で表す
p0 = np.array((1,1)) #点p0の座標
p1 = np.array((6,4)) #点p1の座標
A = p1 - p0          #ベクトルaを示す配列
A

array([5, 3])

In [71]:
#np.linalg.norm()関数にてベクトルaの長さ
a_norm = np.linalg.norm(A)
a_norm

5.830951894845301

In [73]:
#ベクトルaの2倍の長さのベクトル
A2 = A*2
A2

a2_norm = np.linalg.norm(A*2)
a2_norm

11.661903789690601

In [77]:
#sum()メソッドにて配列の要素を合計する
A =np.array([56,45,83,67,59,41]).reshape(2,3)
print(A)

A.sum() #全体の合計

A.sum(0) #各列の合計

A.sum(1) #各行の合計

[[56 45 83]
 [67 59 41]]


array([184, 167])

In [85]:
#max(),min(),mean()メソッドに配列の最大値、最小値、平均値を求める
A.max() #全体の最大値

A.min() #全体の最小値

A.mean() #全体の平均

A.max(0) #各列の最大値

A.min(0) #各列の最小値

A.mean(0) #各列の平均値

A.max(1) #各行の最大値

A.min(1) #各行の最小値

A.mean(1) #各行の平均値

array([61.33333333, 55.66666667])

In [87]:
#numpyの関数を使って配列の最大値を求める
np.sum(A) #Aの合計

np.max(A,1) #Aの各行の最大値

array([83, 67])