In [1]:
import numpy as np

In [7]:
#array()関数で配列を作る
#リストから配列を作る
a = np.array([1,2,3])
a
print(a)

[1 2 3]


In [11]:
#タプルから配列を作る
data = (1,2,3)
a = np.array(data)
a
type(a)
#print(a)

numpy.ndarray

In [12]:
#配列の要素の型を調べる
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [15]:
#型が混在すると配列が作れない

#intとfloat
a = np.array([1,1.5,2]) #全てfloatになる
a

#文字列と数値
b = np.array(["1",1.5,2])#全て文字列になる
b

#論理値と数値
c = np.array([True,False,1.5])#全て数値になる
c

array([1. , 0. , 1.5])

In [18]:
#要素の型を指定して配列を作る

#整数列で作る
a = np.array([1,1.5,2],dtype=int)
a

#浮動小数点型で作る
b = np.array([1,2,3],dtype=float)
b

#複素数型で作る
c = np.array([1,1.5,2],dtype=complex)
c

array([1. +0.j, 1.5+0.j, 2. +0.j])

In [20]:
#文字列に変換して作る
d = np.array([1,1.5,2],dtype="<U")
d

e = np.array([9.123,10.5,12.11],dtype="<U4") #4文字に詰まる
e

array(['9.12', '10.5', '12.1'], dtype='<U4')

In [21]:
#int型の配列をもとにfloat型の配列を作る

a_int = np.array([0,1,2,3,4,5])
a_float = np.array(a_int,dtype=float) #要素の型を変換
a_float

array([0., 1., 2., 3., 4., 5.])

In [23]:
#多重リストから2行3列の配列を作る
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#3X3の配列を作る
line1 = [10,20,30]
line2 = [40,50,60]
line3 = [70,80,90]
a = np.array([line1,line2,line3])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [33]:
#reshape関数にて1次元配列を2行3列の配列に変換する
data = [1,2,3,4,5,6]
a = np.array(data) #リストから配列を作る
a

a = a.reshape(2,3) #2行3列の配列にする
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
#1行のコードで1次元配列を2行3列の配列に変換する
data = [1,2,3,4,5,6]

a = np.array(data).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#ravel()またはflatten()関数にて多次元配列を1次元配列の戻す

#ravel()関数
a = np.array([[0,1],[2,3],[4,5]])
#a.ravel()

#flatten()関数
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [40]:
#shape,ndim関数にて配列の構造を調べる
a = np.array([[0,1],[2,3],[4,5]])
a
#a.shape　#3行2列の配列という事がわかる

a.ndim #2次元配列という事がわかる

2

In [41]:
#size関数にて要素の個数
a = np.array([[0,1],[2,3],[4,5]])
a.size

6

In [43]:
#appen()関数にて要素を追加する
a = np.array([0,1,2])
b = np.append(a,3)  #3を追加する
b

array([0, 1, 2, 3])

In [44]:
#配列に同時に複数の値を追加する
a = np.array([0,1,2])
b = np.append(a,[3,4,5,6,7])
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
#axis=0を使用し2X3の配列に行を追加する(列の追加はaxis=1)
a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

b = np.append(a,[[7,8,9]],axis=0) #axis=0にて行を追加
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
#insert()関数にて配列に要素を挿入する
a = np.array([0,1,2])
b = np.insert(a,1,99) #配列aのインデックス1の位置に99を挿入する
b

array([ 0, 99,  1,  2])

In [51]:
#配列にリスト要素を追加する
a = np.array([0,1,2])
b = np.insert(a,1,[88,99]) #新しい配列bが作られる
b

array([ 0, 88, 99,  1,  2])

In [52]:
#文字列を挿入すると最長の文字列に合わせた長さで切れる
word = np.array(["dog","cat","bird"])
new_word = np.insert(word,0,"snake") #snakeを挿入してもsnekの4文字で切れる
new_word

array(['snak', 'dog', 'cat', 'bird'], dtype='<U4')

In [53]:
#delete()関数にて要素を削除する
words = np.array(["dog","cat","bird"])
new_words = np.delete(words,len(words)-1) #要素から1を引くと最後のインデックスが削除される
new_words

array(['dog', 'cat'], dtype='<U4')